services:
  cua:
    build: .
    container_name: cua
    ports:
      - "3000:3000"  # Your application port
      - "3001:3001"  # Webtop interface port
      - "8080:8080"  # Webserver port
    volumes:
      - ./.env.docker:/app/.env
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped

  bua:
    build:
      context: .
      dockerfile: bua.Dockerfile
    container_name: bua
    ports:
      - "3000:3000"  
      - "3001:3001"  
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - NODE_ENV=production
    volumes:
      - ./.env.docker:/app/.env
      - ./kasmvnc.yaml:/etc/kasmvnc/kasmvnc.yaml
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped