services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "5901:5901" # VNC port for accetto image
      - "3000:3000" # Node.js app
      - "6901:6901" # noVNC web interface port
    # platform: linux/amd64
    restart: unless-stopped
    environment:
      - DOCKER_BUILDKIT=1
      - VNC_RESOLUTION=1024x768
      - VNC_PW=SecurePassword123
    volumes:
      - ./uploads:/app/uploads
      # - ./headless-home:/home/headless
      - ./firefox-profile:/home/headless/.mozilla/firefox