version: '3'

services:
  zenobia-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenobia-vnc-test
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - PORT=3000
      - TZ=Etc/UTC
      - LC_ALL=en_US.UTF-8
      - PORT=3000
      - CUSTOM_PORT=6901
      - TITLE=IRIS
    platform: linux/amd64
    # volumes:
      # - ./docker/xfce4:/config/.config/xfce4
      # - ./assets:/usr/share/selkies/www/assets
    ports:
      - "3000:3000"  # Node.js API
      - "6901:6901"  # KasmVNC web interface
    restart: unless-stopped
    shm_size: 1gb   # Shared memory size for browser performance
    security_opt:
      - seccomp=unconfined  # Required for some modern GUI apps
    # privileged: true  # Gives additional permissions for X server access
