services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "6901:6901"
      - "5901:5901"
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    #   - /app/apps/iris/node_modules
    environment:
      - NODE_ENV=development