# fly.toml app configuration file for iris and minio
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tryiris'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5901
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 6901
  processes = ['app']

  [[services.ports]]
    port = 6901
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 3000
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

# Minio S3 service
[[services]]
  protocol = 'tcp'
  internal_port = 9000
  processes = ['app']

  [[services.ports]]
    port = 9000
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

# Minio Console
[[services]]
  protocol = 'tcp'
  internal_port = 9001
  processes = ['app']

  [[services.ports]]
    port = 9001
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[mounts]]
  source = "iris_vncuser_home"
  destination = "/home/vncuser"
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
