# fly.toml app configuration file generated for zenobia on 2025-04-30T08:15:52+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zenobia'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 6901
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
