services:
  webtop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webtop-nodejs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DISPLAY=:1
      - NODE_PORT=8080
      - WEB_PORT=3000
      - LC_ALL=en_US.UTF-8
    volumes:
      - ./config:/config
      - ./screenshots:/home/nodeuser/app/screenshots
    ports:
      - 8080:8080  # Node.js API
      - 3000:3000  # VNC web interface
    restart: unless-stopped
    shm_size: 1gb